travis:
  secure:
    BINSTAR_TOKEN: gkEpJl6/+O3BmE7FI9a7H+PtUmD1EcVpXeC1RHiSbkBQz9wVGOxtvMuJLWdCawRIRTUKkEEc7TcKsV+Pw4frNDeQzuNFgc22QZqjW4cqIdXBNQYz1C1/uiUtlcukAjtjiOF8rGv+aRNONFTvxCpjVpKKFakUAGgGkomcX/LiMl7R8rtRJ90qNSHNGH8PlR7vB51XBJkemupmOE5oEd1MPScpV2mJbEMKMQTATnexTXUcCoILZVWIr5FReqlbSo/l0d1ag8UM2MJAk17VDeXNT4ugVZIwChMS3k0oaRnNkKnbB6FsIMZb1jVBWw6F4voS6NUskHRHDBtb/QwxKYheiqGBDQo79Bo40hUaYqyRkC1ADSA9uyT4QBCaWVHYiFgVnvosfD3BFhKecjliLBmMFmBmCWgSRxiZygGXJaEKf8//GNlca6f85GpNw7oFqM8S/1xpsSCzvLQyA4E8jHQYY1CtjewZSTWhEnYUZiBAtXBvcBIZWNP8XPanNpLYnyYbLjPjlf5hhqhFlL9uprHP4htfrDf3R2uL2HraDMGatlbQxEW+sDEn4IswhrkJNGnMCB2wK55MLwAVCBdRw7sRAQnahdaMhVK9IhOmO3sAGiEDAHDdEGdzbiSRvTIoFVbPA3q0NJigoM5eQC64y0v79TfYGgVmZ9ANtxVR6ouDubI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
